theme: jekyll-theme-minimal
title: Tabs Lite
description: An open source guitar tablature application built for Android.  Thousands of songs available using an existing popular tabs database. Built for speed and simplicity, 100% free with no ads!
logo: https://raw.githubusercontent.com/cullub/Tabs-Lite/master/docs/img/icon.png